/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektiocr.gjykata;

import projektiocr.*;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import static projektiocr.gjykata.OcrReadGjykata.teDhenatLenda;

/**
 *
 * @author Dell
 */
public class OcrGjykata extends javax.swing.JFrame {

    private String path;
    private String readPath;
    int countTotal = 0;
    int countNenshkruar = 0;
    ConnectionDB con = null;
    OcrReadGjykata read = new OcrReadGjykata();

    /**
     * Creates new form Ocr
     */
    public OcrGjykata() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        con = new ConnectionDB();
        initComponents();
        con.getConnection();
        setTitle("Ocr Project");
        oraData();
    }

    public void oraData() {

        Thread clock = new Thread() {

            public void run() {
                try {
                    while (true) {
                        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss dd-MM-yyyy");
                        Calendar cal = Calendar.getInstance();
                        ora.setText(dateFormat.format(cal.getTime()));
                        sleep(1000);
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }

        };
        clock.start();

    }

    private void addRowToJTable() throws IOException {
//        DefaultTableModel model = (DefaultTableModel) table.getModel();
//
//       model.addRow(new Object[]{OcrReadGjykata.teDhenatLenda});
//
//
//        table.setModel(model);
        jTextArea1.setText(OcrReadGjykata.teDhenatLenda);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        gg = new javax.swing.JLabel();
        openFile = new javax.swing.JButton();
        saveExcel = new javax.swing.JButton();
        saveIn_Database = new javax.swing.JButton();
        readOcr = new javax.swing.JButton();
        gjykata = new javax.swing.JTextField();
        pathiFile_Folder = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        progressBari = new javax.swing.JProgressBar();
        lProgress = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        emri_mbiemri = new javax.swing.JTextField();
        adresa = new javax.swing.JTextField();
        total2 = new javax.swing.JLabel();
        nr_telefonit = new javax.swing.JTextField();
        total3 = new javax.swing.JLabel();
        gjykatsi = new javax.swing.JTextField();
        total4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        generateReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        designOcr = new javax.swing.JButton();
        scanOcr = new javax.swing.JButton();
        Analysis = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ora = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(222, 229, 239));

        gg.setBackground(new java.awt.Color(0, 0, 0));
        gg.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        gg.setForeground(new java.awt.Color(0, 0, 0));
        gg.setText("Gjykata");

        openFile.setBackground(new java.awt.Color(201, 205, 211));
        openFile.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        openFile.setForeground(new java.awt.Color(0, 0, 0));
        openFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_file_33px.png"))); // NOI18N
        openFile.setText("Open File");
        openFile.setHideActionText(true);
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });

        saveExcel.setBackground(new java.awt.Color(201, 205, 211));
        saveExcel.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        saveExcel.setForeground(new java.awt.Color(0, 0, 0));
        saveExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_ms_excel_33px.png"))); // NOI18N
        saveExcel.setText("Save as Excel");
        saveExcel.setHideActionText(true);
        saveExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveExcelActionPerformed(evt);
            }
        });

        saveIn_Database.setBackground(new java.awt.Color(201, 205, 211));
        saveIn_Database.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        saveIn_Database.setForeground(new java.awt.Color(0, 0, 0));
        saveIn_Database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_opened_folder_33px.png"))); // NOI18N
        saveIn_Database.setText("Save in Database");
        saveIn_Database.setHideActionText(true);
        saveIn_Database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveIn_DatabaseActionPerformed(evt);
            }
        });

        readOcr.setBackground(new java.awt.Color(201, 205, 211));
        readOcr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        readOcr.setForeground(new java.awt.Color(0, 0, 0));
        readOcr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_read_message_33px.png"))); // NOI18N
        readOcr.setText("Read Ocr");
        readOcr.setHideActionText(true);
        readOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readOcrActionPerformed(evt);
            }
        });

        gjykata.setCaretColor(new java.awt.Color(255, 255, 255));
        gjykata.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        gjykata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gjykataActionPerformed(evt);
            }
        });

        pathiFile_Folder.setCaretColor(new java.awt.Color(255, 255, 255));
        pathiFile_Folder.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        pathiFile_Folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathiFile_FolderActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Selected File/Folder");

        jPanel4.setBackground(new java.awt.Color(222, 229, 239));
        jPanel4.setForeground(new java.awt.Color(222, 229, 239));

        lProgress.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lProgress.setForeground(new java.awt.Color(0, 0, 0));
        lProgress.setText("0%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(progressBari, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lProgress)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(lProgress))
                    .addComponent(progressBari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        total1.setBackground(new java.awt.Color(0, 0, 0));
        total1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total1.setForeground(new java.awt.Color(0, 0, 0));
        total1.setText("Emri dhe Mbiemri");

        emri_mbiemri.setCaretColor(new java.awt.Color(255, 255, 255));
        emri_mbiemri.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        emri_mbiemri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emri_mbiemriActionPerformed(evt);
            }
        });

        adresa.setCaretColor(new java.awt.Color(255, 255, 255));
        adresa.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        adresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresaActionPerformed(evt);
            }
        });

        total2.setBackground(new java.awt.Color(0, 0, 0));
        total2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total2.setForeground(new java.awt.Color(0, 0, 0));
        total2.setText("Adresa");

        nr_telefonit.setCaretColor(new java.awt.Color(255, 255, 255));
        nr_telefonit.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        nr_telefonit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nr_telefonitActionPerformed(evt);
            }
        });

        total3.setBackground(new java.awt.Color(0, 0, 0));
        total3.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total3.setForeground(new java.awt.Color(0, 0, 0));
        total3.setText("Numri Telefonit");

        gjykatsi.setCaretColor(new java.awt.Color(255, 255, 255));
        gjykatsi.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        gjykatsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gjykatsiActionPerformed(evt);
            }
        });

        total4.setBackground(new java.awt.Color(0, 0, 0));
        total4.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total4.setForeground(new java.awt.Color(0, 0, 0));
        total4.setText("Gjykatsi");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleParent(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LENDA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(pathiFile_Folder, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emri_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gjykata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(total2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(total3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nr_telefonit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(total4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gjykatsi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(406, 406, 406))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(readOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveIn_Database)
                        .addGap(18, 18, 18)
                        .addComponent(saveExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathiFile_Folder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveIn_Database, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(readOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gjykata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emri_mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gjykatsi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nr_telefonit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adresa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1360, 460));

        jPanel2.setBackground(new java.awt.Color(222, 229, 239));

        generateReport.setBackground(new java.awt.Color(201, 205, 211));
        generateReport.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        generateReport.setForeground(new java.awt.Color(0, 0, 0));
        generateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_Report_Card_40px.png"))); // NOI18N
        generateReport.setText("Generate Report");
        generateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gjykata OCR");

        designOcr.setBackground(new java.awt.Color(201, 205, 211));
        designOcr.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        designOcr.setForeground(new java.awt.Color(0, 0, 0));
        designOcr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_design_40px.png"))); // NOI18N
        designOcr.setText("Design OCR");
        designOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designOcrActionPerformed(evt);
            }
        });

        scanOcr.setBackground(new java.awt.Color(201, 205, 211));
        scanOcr.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        scanOcr.setForeground(new java.awt.Color(0, 0, 0));
        scanOcr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_scanner_40px.png"))); // NOI18N
        scanOcr.setLabel("Scan OCR");
        scanOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanOcrActionPerformed(evt);
            }
        });

        Analysis.setBackground(new java.awt.Color(201, 205, 211));
        Analysis.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Analysis.setForeground(new java.awt.Color(0, 0, 0));
        Analysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_bearish_40px.png"))); // NOI18N
        Analysis.setText("Analysis");
        Analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(60, 135, 37));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INSTRUCTION : SELECT THE FOLDER ...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(201, 205, 211));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_close_window_40px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(201, 205, 211));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_minus_40px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ora.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        ora.setForeground(new java.awt.Color(0, 0, 0));

        logout.setBackground(new java.awt.Color(201, 205, 211));
        logout.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 0));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_logout_rounded_up_30px.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(201, 205, 211));
        register.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(0, 0, 0));
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_user_filled_20px.png"))); // NOI18N
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(designOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(scanOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ora, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout)
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(designOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        generateReport.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkInputs() {
        return true;
    }

    public void clear() {
        gjykata.setText("");
        emri_mbiemri.setText("");
        adresa.setText("");
        nr_telefonit.setText("");
        read.clear();
        path = "";
        pathiFile_Folder.setText("");
    }

    public static void fill() {
        try {
            for (int i = 0; i <= 100; i++) {
//                Thread.sleep(10);
                lProgress.setText(Integer.toString(i) + "%");
                progressBari.setValue(i);

            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }


    private void AnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisActionPerformed
//        clear();

    }//GEN-LAST:event_AnalysisActionPerformed

    private void scanOcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanOcrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scanOcrActionPerformed

    private void designOcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designOcrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designOcrActionPerformed

    private void generateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportActionPerformed
        GenerateReport g = new GenerateReport();
        try {
            g.generate();
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        try {
            g.openFile();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_generateReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        Register_Form rf = new Register_Form();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Register_Form rf = new Register_Form();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void gjykatsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gjykatsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gjykatsiActionPerformed

    private void nr_telefonitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nr_telefonitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nr_telefonitActionPerformed

    private void adresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresaActionPerformed

    private void emri_mbiemriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emri_mbiemriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emri_mbiemriActionPerformed

    private void pathiFile_FolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathiFile_FolderActionPerformed

    }//GEN-LAST:event_pathiFile_FolderActionPerformed

    private void gjykataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gjykataActionPerformed

    }//GEN-LAST:event_gjykataActionPerformed

    private void readOcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readOcrActionPerformed
        try {
            OcrReadGjykata read = new OcrReadGjykata();
            read.path(path);
            read.shfaq();
            addRowToJTable();
            fill();
            adresa.setText(OcrReadGjykata.adresa);
            gjykata.setText(OcrReadGjykata.gjykata);
            emri_mbiemri.setText(OcrReadGjykata.emri_mbiemri);
            nr_telefonit.setText(OcrReadGjykata.nrTelit);
            gjykatsi.setText(OcrReadGjykata.emriGjykatsi);

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_readOcrActionPerformed

    private void saveIn_DatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIn_DatabaseActionPerformed
        if (checkInputs()) {
            Connection c = con.getConnection();
            try {
                PreparedStatement ps = (PreparedStatement) c.prepareStatement("insert into gjykata(emri_mbiemri,numri_telefonit,adresa,lenda,gjykata,gjykatsi,date) VALUES(?,?,?,?,?,?,?)");

                OcrReadGjykata read = new OcrReadGjykata();

                List list = OcrRead.studentet;

                ps.setString(1, emri_mbiemri.getText());

                ps.setString(2, nr_telefonit.getText());
                ps.setString(3, adresa.getText());

                ps.setString(4, OcrReadGjykata.teDhenatLenda);

                ps.setString(5, gjykata.getText());
                ps.setString(6, gjykatsi.getText());

                Calendar calendar = Calendar.getInstance();
                SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                ps.setString(7, formatter.format(calendar.getTime()));

                ps.executeUpdate();
                //                System.out.println("riki");
                JOptionPane.showMessageDialog(null, "U ruajten me sukses");

            } catch (SQLException ex) {
                Logger.getLogger(OcrGjykata.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveIn_DatabaseActionPerformed

    private void saveExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExcelActionPerformed
        OcrRead o = new OcrRead();
        try {
            o.saveExcel();
            JOptionPane.showMessageDialog(null, "U ruajten me sukses");
        } catch (Exception ex) {
            Logger.getLogger(OcrGjykata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveExcelActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        pathiFile_Folder.setText(path);
    }//GEN-LAST:event_openFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcrGjykata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcrGjykata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcrGjykata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcrGjykata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

                    new OcrGjykata().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analysis;
    private javax.swing.JTextField adresa;
    private javax.swing.JButton designOcr;
    private javax.swing.JTextField emri_mbiemri;
    private javax.swing.JButton generateReport;
    private javax.swing.JLabel gg;
    private javax.swing.JTextField gjykata;
    private javax.swing.JTextField gjykatsi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel lProgress;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nr_telefonit;
    private javax.swing.JButton openFile;
    private javax.swing.JLabel ora;
    private javax.swing.JTextField pathiFile_Folder;
    public static javax.swing.JProgressBar progressBari;
    private javax.swing.JButton readOcr;
    private javax.swing.JButton register;
    private javax.swing.JButton saveExcel;
    private javax.swing.JButton saveIn_Database;
    private javax.swing.JButton scanOcr;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    private javax.swing.JLabel total3;
    private javax.swing.JLabel total4;
    // End of variables declaration//GEN-END:variables

}
