/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektiocr;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Dell
 */
public class OcrGui extends javax.swing.JFrame {

    private String path;
    private String readPath;
    int countTotal = 0;
    int countNenshkruar = 0;
    ConnectionDB con = null;
    OcrRead read = new OcrRead();

    /**
     * Creates new form Ocr
     */
    public OcrGui() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        con = new ConnectionDB();
        initComponents();
        con.getConnection();
        setTitle("Ocr Project");
        oraData();
    }

    public void oraData() {

        Thread clock = new Thread() {

            public void run() {
                try {
                    while(true){
                    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss dd-MM-yyyy");
                    Calendar cal = Calendar.getInstance();
                    ora.setText(dateFormat.format(cal.getTime()));
                    sleep(1000);
                    }
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }

        };
        clock.start();

    }
    
    private void clearTable(){
        table.setModel(new DefaultTableModel());
    }

    private void addRowToJTable() throws IOException {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        List list = OcrRead.studentet;

        ArrayList<Object[]> datos = new ArrayList<Object[]>();

//        System.out.println("datos "+ datos);
//        System.out.println("list "+ list);
        for (int i = 0; i < list.size(); i++) {
            Object[] inf1 = new Object[]{list.get(i), "I Nenshkurar"};
            datos.add(inf1);
        }
        for (Object[] d : datos) {
            model.addRow(d);
        }

        table.setModel(model);
//        thos.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        openFile = new javax.swing.JButton();
        saveExcel = new javax.swing.JButton();
        saveIn_Database = new javax.swing.JButton();
        readOcr = new javax.swing.JButton();
        paNenshkurar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profa = new javax.swing.JTextField();
        tePanenshkruar = new javax.swing.JTextField();
        teNenshkruar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pathiFile_Folder = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        progressBari = new javax.swing.JProgressBar();
        lProgress = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        lenda = new javax.swing.JTextField();
        orari = new javax.swing.JTextField();
        total2 = new javax.swing.JLabel();
        klasa = new javax.swing.JTextField();
        total3 = new javax.swing.JLabel();
        grupi = new javax.swing.JTextField();
        total4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        generateReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        designOcr = new javax.swing.JButton();
        scanOcr = new javax.swing.JButton();
        Analysis = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ora = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(222, 229, 239));

        total.setBackground(new java.awt.Color(0, 0, 0));
        total.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total.setText("Profa");

        openFile.setBackground(new java.awt.Color(201, 205, 211));
        openFile.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        openFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_file_33px.png"))); // NOI18N
        openFile.setText("Open File");
        openFile.setHideActionText(true);
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });

        saveExcel.setBackground(new java.awt.Color(201, 205, 211));
        saveExcel.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        saveExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_ms_excel_33px.png"))); // NOI18N
        saveExcel.setText("Save as Excel");
        saveExcel.setHideActionText(true);
        saveExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveExcelActionPerformed(evt);
            }
        });

        saveIn_Database.setBackground(new java.awt.Color(201, 205, 211));
        saveIn_Database.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        saveIn_Database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_opened_folder_33px.png"))); // NOI18N
        saveIn_Database.setText("Save in Database");
        saveIn_Database.setHideActionText(true);
        saveIn_Database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveIn_DatabaseActionPerformed(evt);
            }
        });

        readOcr.setBackground(new java.awt.Color(201, 205, 211));
        readOcr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        readOcr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_read_message_33px.png"))); // NOI18N
        readOcr.setText("Read Ocr");
        readOcr.setHideActionText(true);
        readOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readOcrActionPerformed(evt);
            }
        });

        paNenshkurar.setBackground(new java.awt.Color(0, 0, 0));
        paNenshkurar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        paNenshkurar.setText("Te pa nenshkruar");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel5.setText("Te nenshkuruar");

        profa.setCaretColor(new java.awt.Color(255, 255, 255));
        profa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profaActionPerformed(evt);
            }
        });

        tePanenshkruar.setCaretColor(new java.awt.Color(255, 255, 255));
        tePanenshkruar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tePanenshkruarActionPerformed(evt);
            }
        });

        teNenshkruar.setCaretColor(new java.awt.Color(255, 255, 255));
        teNenshkruar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teNenshkruarActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nenshkrimi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        pathiFile_Folder.setCaretColor(new java.awt.Color(255, 255, 255));
        pathiFile_Folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathiFile_FolderActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel7.setText("Selected File/Folder");

        jPanel4.setBackground(new java.awt.Color(222, 229, 239));
        jPanel4.setForeground(new java.awt.Color(222, 229, 239));

        lProgress.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lProgress.setText("0%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(progressBari, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lProgress)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(lProgress))
                    .addComponent(progressBari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        total1.setBackground(new java.awt.Color(0, 0, 0));
        total1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total1.setText("Lenda");

        lenda.setCaretColor(new java.awt.Color(255, 255, 255));
        lenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendaActionPerformed(evt);
            }
        });

        orari.setCaretColor(new java.awt.Color(255, 255, 255));
        orari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orariActionPerformed(evt);
            }
        });

        total2.setBackground(new java.awt.Color(0, 0, 0));
        total2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total2.setText("Orari");

        klasa.setCaretColor(new java.awt.Color(255, 255, 255));
        klasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klasaActionPerformed(evt);
            }
        });

        total3.setBackground(new java.awt.Color(0, 0, 0));
        total3.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total3.setText("Klasa");

        grupi.setCaretColor(new java.awt.Color(255, 255, 255));
        grupi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupiActionPerformed(evt);
            }
        });

        total4.setBackground(new java.awt.Color(0, 0, 0));
        total4.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        total4.setText("Grupi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(pathiFile_Folder, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(profa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(orari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4))
                                                .addComponent(paNenshkurar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(114, 114, 114)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tePanenshkruar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(teNenshkruar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(klasa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(total4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(grupi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(381, 381, 381))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(readOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saveIn_Database)
                                .addGap(18, 18, 18)
                                .addComponent(saveExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathiFile_Folder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveIn_Database, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(readOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(openFile, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(klasa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grupi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teNenshkruar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tePanenshkruar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paNenshkurar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        tePanenshkruar.getAccessibleContext().setAccessibleName("");
        tePanenshkruar.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1360, 460));

        jPanel2.setBackground(new java.awt.Color(222, 229, 239));

        generateReport.setBackground(new java.awt.Color(201, 205, 211));
        generateReport.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        generateReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_Report_Card_40px.png"))); // NOI18N
        generateReport.setText("Generate Report");
        generateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 32)); // NOI18N
        jLabel1.setText("OCR SOFTWARE");

        designOcr.setBackground(new java.awt.Color(201, 205, 211));
        designOcr.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        designOcr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_design_40px.png"))); // NOI18N
        designOcr.setText("Design OCR");
        designOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designOcrActionPerformed(evt);
            }
        });

        scanOcr.setBackground(new java.awt.Color(201, 205, 211));
        scanOcr.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        scanOcr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_scanner_40px.png"))); // NOI18N
        scanOcr.setLabel("Scan OCR");
        scanOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanOcrActionPerformed(evt);
            }
        });

        Analysis.setBackground(new java.awt.Color(201, 205, 211));
        Analysis.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Analysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_bearish_40px.png"))); // NOI18N
        Analysis.setText("Analysis");
        Analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(60, 135, 37));
        jPanel6.setForeground(new java.awt.Color(60, 135, 37));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INSTRUCTION : SELECT THE FOLDER ...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(201, 205, 211));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_close_window_40px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(201, 205, 211));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_minus_40px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ora.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N

        logout.setBackground(new java.awt.Color(201, 205, 211));
        logout.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projektiocrlista/icon/icons8_logout_rounded_up_30px.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(201, 205, 211));
        register.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        register.setText("Clear Table");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(designOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(scanOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ora, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register)
                .addGap(48, 48, 48)
                .addComponent(logout)
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(register))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(designOcr, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        generateReport.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkInputs() {
        return true;
    }

    public void clear() {
        profa.setText("");
        lenda.setText("");
        orari.setText("");
        klasa.setText("");
        DefaultTableModel dm = (DefaultTableModel) table.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        teNenshkruar.setText("");
        tePanenshkruar.setText("");
        read.clear();
        path = "";
        pathiFile_Folder.setText("");
    }

    public static void fill() {
        try {
            for (int i = 0; i <= 100; i++) {
//                Thread.sleep(10);
                lProgress.setText(Integer.toString(i) + "%");
                progressBari.setValue(i);

            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }


    private void AnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisActionPerformed
//        clear();

    }//GEN-LAST:event_AnalysisActionPerformed

    private void scanOcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanOcrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scanOcrActionPerformed

    private void designOcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designOcrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designOcrActionPerformed

    private void generateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportActionPerformed
        GenerateReport g = new GenerateReport();
        try {
            g.generate();
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        try {
            g.openFile();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_generateReportActionPerformed

    private void orariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orariActionPerformed

    private void lendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lendaActionPerformed

    private void pathiFile_FolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathiFile_FolderActionPerformed

    }//GEN-LAST:event_pathiFile_FolderActionPerformed

    private void teNenshkruarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teNenshkruarActionPerformed

    }//GEN-LAST:event_teNenshkruarActionPerformed

    private void tePanenshkruarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tePanenshkruarActionPerformed

    }//GEN-LAST:event_tePanenshkruarActionPerformed

    private void profaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profaActionPerformed

    }//GEN-LAST:event_profaActionPerformed

    private void readOcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readOcrActionPerformed
        
        try {
            OcrRead read = new OcrRead();
            read.path(path);
            read.shfaq();
            addRowToJTable();
            fill();
            orari.setText(OcrRead.orari);
            profa.setText(OcrRead.profa);
            lenda.setText(OcrRead.lenda);
            klasa.setText(OcrRead.klasa);
            grupi.setText(OcrRead.grupi);
            tePanenshkruar.setText(String.valueOf(OcrRead.countTePanenshkruar));
            teNenshkruar.setText(String.valueOf(OcrRead.countNenshkruar));

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_readOcrActionPerformed

    private void saveIn_DatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIn_DatabaseActionPerformed
        if (checkInputs()) {
            Connection c = con.getConnection();
            try {
                PreparedStatement ps = (PreparedStatement) c.prepareStatement("insert into lista(id,nenshkrimi,orari_mesimore,profa,data,lenda,grupi) VALUES(?,?,?,?,?,?,?)");

                OcrRead read = new OcrRead();

                List list = OcrRead.studentet;
                List listPa = OcrRead.studentetPaNenshkruar;

                for (int i = 0; i < list.size(); i++) {
                    ps.setInt(1, Integer.parseInt((String) list.get(i)));
                    ps.setString(2, "I nenshkruar");

                    ps.setString(3, orari.getText());
                    ps.setString(4, profa.getText());

                    Calendar calendar = Calendar.getInstance();
                    SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                    ps.setString(5, formatter.format(calendar.getTime()));

                    ps.setString(6, lenda.getText());
                    ps.setString(7, grupi.getText());

                    ps.executeUpdate();
                    //                System.out.println("riki");
                }
                
                
                                PreparedStatement ps1 = (PreparedStatement) c.prepareStatement("INSERT INTO `listapanenshkruar`(`id`) VALUES (?)");

                for(int i = 0; i < listPa.size();i++){
                    ps1.setInt(1, Integer.parseInt((String) listPa.get(i)));
                    ps1.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "U ruajten me sukses");

            } catch (SQLException ex) {
                Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveIn_DatabaseActionPerformed

    private void saveExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExcelActionPerformed
        OcrRead o = new OcrRead();
        try {
            o.saveExcel();
            JOptionPane.showMessageDialog(null, "U ruajten me sukses");
        } catch (Exception ex) {
            Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveExcelActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        pathiFile_Folder.setText(path);


    }//GEN-LAST:event_openFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void klasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klasaActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
         LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void grupiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupiActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        clearTable();
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcrGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcrGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcrGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcrGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    
                    new OcrGui().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(OcrGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analysis;
    private javax.swing.JButton designOcr;
    private javax.swing.JButton generateReport;
    private javax.swing.JTextField grupi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField klasa;
    public static javax.swing.JLabel lProgress;
    private javax.swing.JTextField lenda;
    private javax.swing.JButton logout;
    private javax.swing.JButton openFile;
    private javax.swing.JLabel ora;
    private javax.swing.JTextField orari;
    private javax.swing.JLabel paNenshkurar;
    private javax.swing.JTextField pathiFile_Folder;
    private javax.swing.JTextField profa;
    public static javax.swing.JProgressBar progressBari;
    private javax.swing.JButton readOcr;
    private javax.swing.JButton register;
    private javax.swing.JButton saveExcel;
    private javax.swing.JButton saveIn_Database;
    private javax.swing.JButton scanOcr;
    private javax.swing.JTable table;
    private javax.swing.JTextField teNenshkruar;
    private javax.swing.JTextField tePanenshkruar;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    private javax.swing.JLabel total3;
    private javax.swing.JLabel total4;
    // End of variables declaration//GEN-END:variables

}
